apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx
spec:
  secretName: nginx-tls
  duration: 720h
  dnsNames:
    - nginx.default.hello123.tk
  issuerRef:
    name: my-ca
    kind: Issuer
    group: cert-manager.io
